<?php

return [
	'CORE' => [
		'core',
		'env',
		'config',
		'model/database',
		'model/DB',
		'model/modelCore',
		'model/modelObject',
		'model/modelSql',
		'model/modelMethods',
		'model/model',
		'controllerCore',
		'view/e',
		'view/errors',
		'view/compiler',
		'view/view',
		'response/responseObject',
		'response/response',
		'route/route_core',
		'route/route_instance',
		'route/route_console',
		'route/route_web',
		'exception',
		'middleware',
		'request/validateIs',
		'request/validate',
		'request/objects/file',
		'request/objects/files',
		'request/request',
		'app',
		'lang',
		'log',
	]
];